UILD-344: Update profile to accommodate authority search
FOLIO-EIS/mod-linked-data pull request #309
Opened 2024-07-26 18:42 UTC by pkjacob

2024-07-26 19:07 UTC, SKarolFolio requested changes
Here you can find the profile example with the latest changes:
[https://folio-org.atlassian.net/browse/UILD-344](https://folio-org.atlassian.net/browse/UILD-344)

Some additional fields have been added there compared to the version in the current PR

2024-07-26 20:46 UTC, pkjacob commented
Thank you for pointing out the mistake @SKarolFolio. Fixed it now.

2024-07-27 06:18 UTC, SKarolFolio approved these changes

2024-07-29 04:19 UTC, askhat-abishev approved these changes

2024-07-30 20:23 UTC, merged